// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Backend.Migrations
{
    [DbContext(typeof(ProdukcijaContext))]
    [Migration("20220317145926_V2")]
    partial class V2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Igrica", b =>
                {
                    b.Property<int>("IDIgrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NazivIgre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Poeni1")
                        .HasColumnType("int");

                    b.Property<int>("Poeni2")
                        .HasColumnType("int");

                    b.Property<int?>("kvizIDKviza")
                        .HasColumnType("int");

                    b.HasKey("IDIgrice");

                    b.HasIndex("kvizIDKviza");

                    b.ToTable("Igrice");
                });

            modelBuilder.Entity("Models.Kviz", b =>
                {
                    b.Property<int>("IDKviza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojIgara")
                        .HasColumnType("int");

                    b.Property<int>("BrojPartija")
                        .HasColumnType("int");

                    b.Property<int>("BrojTakmicara")
                        .HasColumnType("int");

                    b.Property<string>("NazivKviza")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDKviza");

                    b.ToTable("Kvizovi");
                });

            modelBuilder.Entity("Models.Partija", b =>
                {
                    b.Property<int>("IDPartija")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dan")
                        .HasColumnType("int");

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<int>("IDTakm1")
                        .HasColumnType("int");

                    b.Property<int>("IDTakm2")
                        .HasColumnType("int");

                    b.Property<string>("Mesec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RedniBroj")
                        .HasColumnType("int");

                    b.Property<int?>("Takmicar1IDTakmicar")
                        .HasColumnType("int");

                    b.Property<int?>("Takmicar2IDTakmicar")
                        .HasColumnType("int");

                    b.Property<int?>("kvizIDKviza")
                        .HasColumnType("int");

                    b.HasKey("IDPartija");

                    b.HasIndex("Takmicar1IDTakmicar");

                    b.HasIndex("Takmicar2IDTakmicar");

                    b.HasIndex("kvizIDKviza");

                    b.ToTable("Partije");
                });

            modelBuilder.Entity("Models.Rezultat", b =>
                {
                    b.Property<int>("idRez")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("igricaIDIgrice")
                        .HasColumnType("int");

                    b.Property<int?>("kvizIDKviza")
                        .HasColumnType("int");

                    b.Property<int?>("partijaIDPartija")
                        .HasColumnType("int");

                    b.Property<int>("takm1Poeni")
                        .HasColumnType("int");

                    b.Property<int>("takm2Poeni")
                        .HasColumnType("int");

                    b.HasKey("idRez");

                    b.HasIndex("igricaIDIgrice");

                    b.HasIndex("kvizIDKviza");

                    b.HasIndex("partijaIDPartija");

                    b.ToTable("Rezultati");
                });

            modelBuilder.Entity("Models.Takmicar", b =>
                {
                    b.Property<int>("IDTakmicar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojPoena")
                        .HasColumnType("int");

                    b.Property<int>("GodinaRodjenja")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("OdigranePartije")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Zanimanje")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("kvizIDKviza")
                        .HasColumnType("int");

                    b.HasKey("IDTakmicar");

                    b.HasIndex("kvizIDKviza");

                    b.ToTable("Takmicari");
                });

            modelBuilder.Entity("Models.Igrica", b =>
                {
                    b.HasOne("Models.Kviz", "kviz")
                        .WithMany()
                        .HasForeignKey("kvizIDKviza");

                    b.Navigation("kviz");
                });

            modelBuilder.Entity("Models.Partija", b =>
                {
                    b.HasOne("Models.Takmicar", "Takmicar1")
                        .WithMany()
                        .HasForeignKey("Takmicar1IDTakmicar");

                    b.HasOne("Models.Takmicar", "Takmicar2")
                        .WithMany()
                        .HasForeignKey("Takmicar2IDTakmicar");

                    b.HasOne("Models.Kviz", "kviz")
                        .WithMany()
                        .HasForeignKey("kvizIDKviza");

                    b.Navigation("kviz");

                    b.Navigation("Takmicar1");

                    b.Navigation("Takmicar2");
                });

            modelBuilder.Entity("Models.Rezultat", b =>
                {
                    b.HasOne("Models.Igrica", "igrica")
                        .WithMany()
                        .HasForeignKey("igricaIDIgrice");

                    b.HasOne("Models.Kviz", "kviz")
                        .WithMany()
                        .HasForeignKey("kvizIDKviza");

                    b.HasOne("Models.Partija", "partija")
                        .WithMany("RezultatPartija")
                        .HasForeignKey("partijaIDPartija");

                    b.Navigation("igrica");

                    b.Navigation("kviz");

                    b.Navigation("partija");
                });

            modelBuilder.Entity("Models.Takmicar", b =>
                {
                    b.HasOne("Models.Kviz", "kviz")
                        .WithMany("TakmicariKviz")
                        .HasForeignKey("kvizIDKviza");

                    b.Navigation("kviz");
                });

            modelBuilder.Entity("Models.Kviz", b =>
                {
                    b.Navigation("TakmicariKviz");
                });

            modelBuilder.Entity("Models.Partija", b =>
                {
                    b.Navigation("RezultatPartija");
                });
#pragma warning restore 612, 618
        }
    }
}
